AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/console
    - active_any.gemspec
    - Guardfile
    - vendor/bundle/**/*
  DisplayCopNames: true

Style/Documentation:
  Enabled: false

Style/PredicateName:
  Enabled: false

Metrics/LineLength:
  Max: 150
  Exclude:
    - test/**/*

Style/GuardClause:
  Enabled: false

Metrics/AbcSize:
  Max: 18
  Exclude:
    - test/**/*
