AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - bin/console
    - active_any.gemspec
    - Guardfile
    - vendor/bundle/**/*
  DisplayCopNames: true

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 128

Metrics/AbcSize:
  Exclude:
    - test/**/*
